---
- name: "Configure Device"
  hosts: srx
  connection: local
  gather_facts: yes
  vars:
    cluster_device_commit_check: true
    cluster_device_commit: true
    ansible_python_path: python3
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - Juniper.junos

  tasks:
    - name: Print debug information
      when: false
      debug:
        msg: "{{ hostvars }}"

    - name: Print debug information
      debug:
        msg: "{{ ansible_host }}"

    - name: Print debug information
      debug:
        msg: "{{ inventory_hostname }}"

    - name: "Wait for ssh"
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        delay: 1
        sleep: 30
        timeout: 60

    - name: "Wait for netconf"
      wait_for:
        port: 830
        host: "{{ ansible_host }}"
        delay: 1
        sleep: 30
        timeout: 60

    - name: Merge user configuration from a file and commit
      juniper_junos_config:
        load: "merge"
        format: "text"
        #src: "simple.conf"
        src: "vsrx1.conf"
        comment: "Configuring user configuration with Ansible"
        ignore_warning:
          - "statement has no contents; ignored"
        provider:
          host: "{{ ansible_host }}"
          username: "root"
          password: "c0ntrail123!"
          timeout: 360
      register: merge_res

    #- name: Print the response
      #debug:
        #var: merge_res
